BethaniesPieShop/BethaniesPieShop/Controllers/FeedbackController.cs
using BethaniesPieShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace BethaniesPieShop.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepository _feedbackRepository;

        public FeedbackController(IFeedbackRepository feedbackFeedbackRepository)
        {
            _feedbackRepository = feedbackFeedbackRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedback(feedback);

                return RedirectToAction("FeedbackComplete");
            }

            return View(feedback);
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

BethaniesPieShop/BethaniesPieShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/content/site.css" />
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Bethany's Pie Shop</a></li>
                    <li><a asp-controller="Feedback" asp-action="Index">Feedback</a></li>
                </ul>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                            </ul>
                        </form>
                    }
                    else { 
                        <ul class="nav navbar-nav navbar-right">
                               <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
                               <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
                         </ul>
                    }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
</body>
</html>